version: "3.9"

x-test-framework: jest

x-service:
  &service
  build:
    context: ..
    dockerfile: .engi/Dockerfile.tests
  volumes:
    - type: volume
      source: output
      target: $ENGI_WORKING_DIR

services:
  tests:
    command: /bin/sh -c "jest --json | tee $ENGI_WORKING_DIR/jest.json"
    <<: *service
    environment:
      - STORYBOOK_HOSTNAME=storybook
      - STORYBOOK_PORT=6008
      - STORYBOOK_PREFERS_DARK=true
volumes:
  output:
    external: true
    name: $ENGI_WORKING_VOL
