version: "3.9"

x-test-framework: jest

x-service:
  &service
  build:
    context: ..
    dockerfile: .engi/tests.Dockerfile
  volumes:
    - type: volume
      source: output
      target: $ENGI_WORKING_DIR

services:
  tests:
    command: /bin/sh -c "jest --json | tee $ENGI_WORKING_DIR/jest.json"
    <<: *service
volumes:
  output:
    external: true
    name: $ENGI_WORKING_VOL
